version: '3.10'
services:
  yt-converter_dev:
    container_name: yt-converter_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: '/root/yt-converter'
    tty: true
    volumes:
      - ./yt-converter:/root/yt-converter
      - /var/www/yt-converter/staticfiles:/var/www/yt-converter/staticfiles
    image: yt-converter
    env_file:
      - .env

  nginx_dev:
    container_name: nginx_dev
    build:
      context: .
      dockerfile: Dockerfile.dev.nginx
    ports:
      - "80:80"
    image: yt-converter-nginx
    depends_on:
      - yt-converter_dev
    volumes:
      - /var/www/yt-converter/staticfiles:/var/www/yt-converter/staticfiles
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf

  yt-converter_prod:
    container_name: yt-converter_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    working_dir: '/root/yt-converter'
    tty: true
    volumes:
      - ./yt-converter:/root/yt-converter
      - /var/www/yt-converter/staticfiles:/var/www/yt-converter/staticfiles
    image: yt-converter
    env_file:
      - .env

  nginx_prod:
    container_name: nginx_prod
    build:
      context: .
      dockerfile: Dockerfile.prod.nginx
    ports:
      - "80:80"
    image: yt-converter-nginx
    depends_on:
      - yt-converter_prod
    volumes:
      - /var/www/yt-converter/staticfiles:/var/www/yt-converter/staticfiles
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf