FROM python:3
USER root
RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

# libcap2-binはgunicornに特定の権限（ここではポート番号1024未満のポートにもバインド可能にする）
RUN apt-get update
RUN apt-get install -y vim less libcap2-bin
RUN apt-get -y install ffmpeg
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN python -m pip install django
RUN python -m pip install django-environ
RUN python -m pip install django-storages  # S3用
RUN python -m pip install boto3            # S3用
RUN python -m pip install yt-dlp
RUN python -m pip install gunicorn
# gunicornのプロセスにcap_net_bind_serviceというケイパビリティを設定し、ポート番号1024未満のポートにもバインド可能にする
RUN setcap 'cap_net_bind_service=+ep' /usr/local/bin/gunicorn
RUN mkdir -p /var/log/gunicorn/

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs
RUN npm install